// 権限レベル
const USER_ROLE_LEVEL_CUSTERMER: number = 0;
const USER_ROLE_LEVEL_EMPLOYEE: number = 1;
const USER_ROLE_LEVEL_MANAGER: number = 2;
const USER_ROLE_LEVEL_ADMINISTRATOR: number = 3;

export { USER_ROLE_LEVEL_CUSTERMER, USER_ROLE_LEVEL_EMPLOYEE, USER_ROLE_LEVEL_MANAGER, USER_ROLE_LEVEL_ADMINISTRATOR };
